package view.root;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.border.EmptyBorder;
import model.beans.Grade;
import model.beans.Student;
import model.beans.SubjectDetail;
import service.Service;
import service.StudentService;
import view.ultilities.LoadingDialog;
import view.login.Login;
import static view.login.Login.load;

/**
 *
 * @author nguye
 */
public class StudentView extends javax.swing.JFrame {

    /**
     * Creates new form StudentView
     */
    private String username;
    private final Service service;
    private final StudentService studentService;
    private final Student studentObj;
    private final CardLayout cardLayout;
    private List<SubjectDetail> listSubjectForGrade;
    private TreeMap<String, Integer> mapSubjectForGrade;
    private final DefaultListModel<String> modelSubjectForGrade;
    private Grade grade;
    private List<SubjectDetail> listSubjectHaveStudied;
    private TreeMap<String, Integer> mapSubjectHaveStudied;
    private final DefaultListModel<String> modelSubjectHaveStudied;

    public StudentView(String username) {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                Login.load.dispose();
            }
        });
        initComponents();
        this.username = username;
        setLocationRelativeTo(null);

        // service 
        service = new Service();
        studentService = new StudentService();

        // Lấy layout
        cardLayout = (CardLayout) Cards.getLayout();

        // create student obj
        studentObj = studentService.createStudentObj(username);
        setTitle("Xin chào " + studentObj.getStudentName());

        getContentPane().setBackground(new Color(0xffffff));
        designButton(jButton1, 0xffffff, 0x2f3542, 10, 25, 10, 25);
        designButton(btnGrade, 0xffffff, 0x2f3542, 10, 25, 10, 25);
        designButton(btnAttendance, 0xffffff, 0x2f3542, 10, 25, 10, 25);
        designButton(btnProfile, 0xffffff, 0x2f3542, 10, 25, 10, 25);

        // model
        modelSubjectForGrade = new DefaultListModel<String>();
        modelSubjectHaveStudied = new DefaultListModel<String>();

        initSubjectForGrade();
        initInfoStudent();
        initListSubjectHaveStudied();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelButton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnGrade = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        Cards = new javax.swing.JPanel();
        panelNews = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        panelGrade = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelListSubjects = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlListSubjects = new javax.swing.JList<>();
        panelQuiz1 = new javax.swing.JPanel();
        txtQuiz1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelQuiz2 = new javax.swing.JPanel();
        txtQuiz2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelQuiz3 = new javax.swing.JPanel();
        txtQuiz3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelQuiz4 = new javax.swing.JPanel();
        txtQuiz4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelQuiz5 = new javax.swing.JPanel();
        txtQuiz5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelQuiz6 = new javax.swing.JPanel();
        txtQuiz6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelQuiz7 = new javax.swing.JPanel();
        txtQuiz7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelQuiz8 = new javax.swing.JPanel();
        txtQuiz8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        panelLab1 = new javax.swing.JPanel();
        txtLab1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        panelLab2 = new javax.swing.JPanel();
        txtLab2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        panelLab3 = new javax.swing.JPanel();
        txtLab3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panelLab4 = new javax.swing.JPanel();
        txtLab4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panelLab5 = new javax.swing.JPanel();
        txtLab5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        panelLab6 = new javax.swing.JPanel();
        txtLab6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        panelLab7 = new javax.swing.JPanel();
        txtLab7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        panelLab8 = new javax.swing.JPanel();
        txtLab8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        panelASM1 = new javax.swing.JPanel();
        txtASM1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        panelASM2 = new javax.swing.JPanel();
        txtASM2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        panelASMFinal = new javax.swing.JPanel();
        txtASMFinal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        panelAverage = new javax.swing.JPanel();
        txtAverage = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        panelAttendance = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        panelL = new javax.swing.JPanel();
        panelImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblNameStudent = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        panelEmail = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        panelSex = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        panelEmail3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtProvice = new javax.swing.JTextField();
        panelPhoneNumber = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        panelDob = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        panelSpecificallyMajor = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtSpecificallyMajor = new javax.swing.JTextField();
        panelJoinDate = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtJoinDate = new javax.swing.JTextField();
        panelBatch = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        panelDescriptor = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtDescriptor = new javax.swing.JTextField();
        panlR = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlSubjectsR = new javax.swing.JList<>();
        jLabel34 = new javax.swing.JLabel();
        Info = new javax.swing.JPanel();
        txtAverageR = new javax.swing.JTextField();
        txtStatusR = new javax.swing.JTextField();
        txtTeacherName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setText("News");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelButton.add(jButton1);

        btnGrade.setText("Grade");
        btnGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeActionPerformed(evt);
            }
        });
        panelButton.add(btnGrade);

        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        panelButton.add(btnAttendance);

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        panelButton.add(btnProfile);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(panelButton, gridBagConstraints);

        Cards.setLayout(new java.awt.CardLayout());

        panelNews.setBackground(new java.awt.Color(44, 62, 80));
        panelNews.setMinimumSize(new java.awt.Dimension(152, 17));
        panelNews.setLayout(new java.awt.GridBagLayout());

        lblTittle.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(236, 240, 241));
        lblTittle.setText("Đang phát triển ...");
        panelNews.add(lblTittle, new java.awt.GridBagConstraints());

        Cards.add(panelNews, "cardNews");

        panelGrade.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin điểm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        panelGrade.add(jLabel1, gridBagConstraints);

        panelListSubjects.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jLabel2.setText("Danh sách môn học");
        panelListSubjects.add(jLabel2, java.awt.BorderLayout.NORTH);

        jlListSubjects.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jlListSubjects.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlListSubjectsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlListSubjects);

        panelListSubjects.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelListSubjects, gridBagConstraints);

        panelQuiz1.setLayout(new java.awt.BorderLayout());

        txtQuiz1.setEditable(false);
        txtQuiz1.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz1.setColumns(8);
        txtQuiz1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz1.setForeground(new java.awt.Color(47, 53, 66));
        txtQuiz1.setText("6");
        panelQuiz1.add(txtQuiz1, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Quiz 1");
        panelQuiz1.add(jLabel3, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz1, gridBagConstraints);

        panelQuiz2.setLayout(new java.awt.BorderLayout());

        txtQuiz2.setEditable(false);
        txtQuiz2.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz2.setColumns(8);
        txtQuiz2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz2.setForeground(new java.awt.Color(47, 53, 66));
        txtQuiz2.setText("9");
        panelQuiz2.add(txtQuiz2, java.awt.BorderLayout.CENTER);

        jLabel4.setText("Quiz 2");
        panelQuiz2.add(jLabel4, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz2, gridBagConstraints);

        panelQuiz3.setLayout(new java.awt.BorderLayout());

        txtQuiz3.setEditable(false);
        txtQuiz3.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz3.setColumns(8);
        txtQuiz3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz3.setForeground(new java.awt.Color(47, 53, 66));
        txtQuiz3.setText("1");
        panelQuiz3.add(txtQuiz3, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Quiz 3");
        panelQuiz3.add(jLabel5, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz3, gridBagConstraints);

        panelQuiz4.setLayout(new java.awt.BorderLayout());

        txtQuiz4.setEditable(false);
        txtQuiz4.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz4.setColumns(8);
        txtQuiz4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz4.setForeground(new java.awt.Color(47, 53, 66));
        panelQuiz4.add(txtQuiz4, java.awt.BorderLayout.CENTER);

        jLabel6.setText("Quiz 4");
        panelQuiz4.add(jLabel6, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz4, gridBagConstraints);

        panelQuiz5.setLayout(new java.awt.BorderLayout());

        txtQuiz5.setEditable(false);
        txtQuiz5.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz5.setColumns(8);
        txtQuiz5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz5.setForeground(new java.awt.Color(47, 53, 66));
        panelQuiz5.add(txtQuiz5, java.awt.BorderLayout.CENTER);

        jLabel7.setText("Quiz 5");
        panelQuiz5.add(jLabel7, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz5, gridBagConstraints);

        panelQuiz6.setLayout(new java.awt.BorderLayout());

        txtQuiz6.setEditable(false);
        txtQuiz6.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz6.setColumns(8);
        txtQuiz6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz6.setForeground(new java.awt.Color(47, 53, 66));
        txtQuiz6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuiz6ActionPerformed(evt);
            }
        });
        panelQuiz6.add(txtQuiz6, java.awt.BorderLayout.CENTER);

        jLabel8.setText("Quiz 6");
        panelQuiz6.add(jLabel8, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz6, gridBagConstraints);

        panelQuiz7.setLayout(new java.awt.BorderLayout());

        txtQuiz7.setEditable(false);
        txtQuiz7.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz7.setColumns(8);
        txtQuiz7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz7.setForeground(new java.awt.Color(47, 53, 66));
        panelQuiz7.add(txtQuiz7, java.awt.BorderLayout.CENTER);

        jLabel9.setText("Quiz 7");
        panelQuiz7.add(jLabel9, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz7, gridBagConstraints);

        panelQuiz8.setLayout(new java.awt.BorderLayout());

        txtQuiz8.setEditable(false);
        txtQuiz8.setBackground(new java.awt.Color(255, 255, 255));
        txtQuiz8.setColumns(8);
        txtQuiz8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQuiz8.setForeground(new java.awt.Color(47, 53, 66));
        panelQuiz8.add(txtQuiz8, java.awt.BorderLayout.CENTER);

        jLabel10.setText("Quiz 8");
        panelQuiz8.add(jLabel10, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelQuiz8, gridBagConstraints);

        panelLab1.setLayout(new java.awt.BorderLayout());

        txtLab1.setEditable(false);
        txtLab1.setBackground(new java.awt.Color(255, 255, 255));
        txtLab1.setColumns(8);
        txtLab1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab1.setForeground(new java.awt.Color(47, 53, 66));
        panelLab1.add(txtLab1, java.awt.BorderLayout.CENTER);

        jLabel11.setText("Lab 1");
        panelLab1.add(jLabel11, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab1, gridBagConstraints);

        panelLab2.setLayout(new java.awt.BorderLayout());

        txtLab2.setEditable(false);
        txtLab2.setBackground(new java.awt.Color(255, 255, 255));
        txtLab2.setColumns(8);
        txtLab2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab2.setForeground(new java.awt.Color(47, 53, 66));
        panelLab2.add(txtLab2, java.awt.BorderLayout.CENTER);

        jLabel12.setText("Lab 2");
        panelLab2.add(jLabel12, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab2, gridBagConstraints);

        panelLab3.setLayout(new java.awt.BorderLayout());

        txtLab3.setEditable(false);
        txtLab3.setBackground(new java.awt.Color(255, 255, 255));
        txtLab3.setColumns(8);
        txtLab3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab3.setForeground(new java.awt.Color(47, 53, 66));
        panelLab3.add(txtLab3, java.awt.BorderLayout.CENTER);

        jLabel13.setText("Lab 3");
        panelLab3.add(jLabel13, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab3, gridBagConstraints);

        panelLab4.setLayout(new java.awt.BorderLayout());

        txtLab4.setEditable(false);
        txtLab4.setBackground(new java.awt.Color(255, 255, 255));
        txtLab4.setColumns(8);
        txtLab4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab4.setForeground(new java.awt.Color(47, 53, 66));
        panelLab4.add(txtLab4, java.awt.BorderLayout.CENTER);

        jLabel14.setText("Lab 4");
        panelLab4.add(jLabel14, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab4, gridBagConstraints);

        panelLab5.setLayout(new java.awt.BorderLayout());

        txtLab5.setEditable(false);
        txtLab5.setBackground(new java.awt.Color(255, 255, 255));
        txtLab5.setColumns(8);
        txtLab5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab5.setForeground(new java.awt.Color(47, 53, 66));
        txtLab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab5ActionPerformed(evt);
            }
        });
        panelLab5.add(txtLab5, java.awt.BorderLayout.CENTER);

        jLabel15.setText("Lab 5");
        panelLab5.add(jLabel15, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab5, gridBagConstraints);

        panelLab6.setLayout(new java.awt.BorderLayout());

        txtLab6.setEditable(false);
        txtLab6.setBackground(new java.awt.Color(255, 255, 255));
        txtLab6.setColumns(8);
        txtLab6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab6.setForeground(new java.awt.Color(47, 53, 66));
        panelLab6.add(txtLab6, java.awt.BorderLayout.CENTER);

        jLabel16.setText("Lab 6");
        panelLab6.add(jLabel16, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab6, gridBagConstraints);

        panelLab7.setLayout(new java.awt.BorderLayout());

        txtLab7.setEditable(false);
        txtLab7.setBackground(new java.awt.Color(255, 255, 255));
        txtLab7.setColumns(8);
        txtLab7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab7.setForeground(new java.awt.Color(47, 53, 66));
        panelLab7.add(txtLab7, java.awt.BorderLayout.CENTER);

        jLabel17.setText("Lab 7");
        panelLab7.add(jLabel17, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab7, gridBagConstraints);

        panelLab8.setLayout(new java.awt.BorderLayout());

        txtLab8.setEditable(false);
        txtLab8.setBackground(new java.awt.Color(255, 255, 255));
        txtLab8.setColumns(8);
        txtLab8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLab8.setForeground(new java.awt.Color(47, 53, 66));
        panelLab8.add(txtLab8, java.awt.BorderLayout.CENTER);

        jLabel18.setText("Lab 8");
        panelLab8.add(jLabel18, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelLab8, gridBagConstraints);

        panelASM1.setLayout(new java.awt.BorderLayout());

        txtASM1.setEditable(false);
        txtASM1.setBackground(new java.awt.Color(255, 255, 255));
        txtASM1.setColumns(8);
        txtASM1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtASM1.setForeground(new java.awt.Color(47, 53, 66));
        panelASM1.add(txtASM1, java.awt.BorderLayout.CENTER);

        jLabel19.setText("Assignment 1");
        panelASM1.add(jLabel19, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelASM1, gridBagConstraints);

        panelASM2.setLayout(new java.awt.BorderLayout());

        txtASM2.setEditable(false);
        txtASM2.setBackground(new java.awt.Color(255, 255, 255));
        txtASM2.setColumns(8);
        txtASM2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtASM2.setForeground(new java.awt.Color(47, 53, 66));
        panelASM2.add(txtASM2, java.awt.BorderLayout.CENTER);

        jLabel20.setText("Assignment 2");
        panelASM2.add(jLabel20, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelASM2, gridBagConstraints);

        panelASMFinal.setLayout(new java.awt.BorderLayout());

        txtASMFinal.setEditable(false);
        txtASMFinal.setBackground(new java.awt.Color(255, 255, 255));
        txtASMFinal.setColumns(8);
        txtASMFinal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtASMFinal.setForeground(new java.awt.Color(47, 53, 66));
        panelASMFinal.add(txtASMFinal, java.awt.BorderLayout.CENTER);

        jLabel21.setText("Final");
        panelASMFinal.add(jLabel21, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelASMFinal, gridBagConstraints);

        panelAverage.setLayout(new java.awt.BorderLayout());

        txtAverage.setEditable(false);
        txtAverage.setBackground(new java.awt.Color(255, 255, 255));
        txtAverage.setColumns(8);
        txtAverage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelAverage.add(txtAverage, java.awt.BorderLayout.CENTER);

        jLabel22.setText("Average");
        panelAverage.add(jLabel22, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelGrade.add(panelAverage, gridBagConstraints);

        lblStatus.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelGrade.add(lblStatus, gridBagConstraints);

        Cards.add(panelGrade, "cardGrade");

        javax.swing.GroupLayout panelAttendanceLayout = new javax.swing.GroupLayout(panelAttendance);
        panelAttendance.setLayout(panelAttendanceLayout);
        panelAttendanceLayout.setHorizontalGroup(
            panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1193, Short.MAX_VALUE)
        );
        panelAttendanceLayout.setVerticalGroup(
            panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        Cards.add(panelAttendance, "cardAttendance");

        panel.setBackground(new java.awt.Color(52, 152, 219));
        panel.setLayout(new java.awt.GridBagLayout());

        panelL.setBackground(new java.awt.Color(237, 76, 103));
        panelL.setLayout(new java.awt.GridBagLayout());

        panelImage.setBackground(new java.awt.Color(39, 174, 96));
        panelImage.setMinimumSize(new java.awt.Dimension(120, 120));
        panelImage.setPreferredSize(new java.awt.Dimension(120, 120));
        panelImage.setLayout(new java.awt.GridBagLayout());

        lblImage.setText("NOTHING");
        panelImage.add(lblImage, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 5, 0);
        panelL.add(panelImage, gridBagConstraints);

        lblNameStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNameStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblNameStudent.setText("Full name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelL.add(lblNameStudent, gridBagConstraints);

        lblStudentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStudentID.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentID.setText("Student ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 7, 10);
        panelL.add(lblStudentID, gridBagConstraints);

        panelEmail.setBackground(new java.awt.Color(237, 76, 103));
        panelEmail.setLayout(new java.awt.BorderLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Email");
        panelEmail.add(jLabel23, java.awt.BorderLayout.NORTH);

        txtEmail.setEditable(false);
        txtEmail.setColumns(24);
        panelEmail.add(txtEmail, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelEmail, gridBagConstraints);

        panelSex.setBackground(new java.awt.Color(237, 76, 103));
        panelSex.setLayout(new java.awt.BorderLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Giới tính");
        panelSex.add(jLabel24, java.awt.BorderLayout.NORTH);

        txtSex.setEditable(false);
        txtSex.setColumns(24);
        txtSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexActionPerformed(evt);
            }
        });
        panelSex.add(txtSex, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelSex, gridBagConstraints);

        panelEmail3.setBackground(new java.awt.Color(237, 76, 103));
        panelEmail3.setLayout(new java.awt.BorderLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tỉnh / thành phố");
        panelEmail3.add(jLabel26, java.awt.BorderLayout.NORTH);

        txtProvice.setEditable(false);
        txtProvice.setColumns(24);
        panelEmail3.add(txtProvice, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelEmail3, gridBagConstraints);

        panelPhoneNumber.setBackground(new java.awt.Color(237, 76, 103));
        panelPhoneNumber.setLayout(new java.awt.BorderLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Số điện thoại");
        panelPhoneNumber.add(jLabel25, java.awt.BorderLayout.NORTH);

        txtPhoneNumber.setEditable(false);
        txtPhoneNumber.setColumns(24);
        panelPhoneNumber.add(txtPhoneNumber, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelPhoneNumber, gridBagConstraints);

        panelDob.setBackground(new java.awt.Color(237, 76, 103));
        panelDob.setLayout(new java.awt.BorderLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ngày sinh");
        panelDob.add(jLabel27, java.awt.BorderLayout.NORTH);

        txtDob.setEditable(false);
        txtDob.setColumns(24);
        panelDob.add(txtDob, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelDob, gridBagConstraints);

        panelSpecificallyMajor.setBackground(new java.awt.Color(237, 76, 103));
        panelSpecificallyMajor.setLayout(new java.awt.BorderLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Ngành hẹp");
        panelSpecificallyMajor.add(jLabel28, java.awt.BorderLayout.NORTH);

        txtSpecificallyMajor.setEditable(false);
        txtSpecificallyMajor.setColumns(24);
        panelSpecificallyMajor.add(txtSpecificallyMajor, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelSpecificallyMajor, gridBagConstraints);

        panelJoinDate.setBackground(new java.awt.Color(237, 76, 103));
        panelJoinDate.setLayout(new java.awt.BorderLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Ngày nhập học");
        panelJoinDate.add(jLabel29, java.awt.BorderLayout.NORTH);

        txtJoinDate.setEditable(false);
        txtJoinDate.setColumns(24);
        panelJoinDate.add(txtJoinDate, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelJoinDate, gridBagConstraints);

        panelBatch.setBackground(new java.awt.Color(237, 76, 103));
        panelBatch.setLayout(new java.awt.BorderLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Khóa");
        panelBatch.add(jLabel30, java.awt.BorderLayout.NORTH);

        txtBatch.setEditable(false);
        txtBatch.setColumns(24);
        panelBatch.add(txtBatch, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelBatch, gridBagConstraints);

        panelDescriptor.setBackground(new java.awt.Color(237, 76, 103));
        panelDescriptor.setLayout(new java.awt.BorderLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Mô tả");
        panelDescriptor.add(jLabel31, java.awt.BorderLayout.NORTH);

        txtDescriptor.setEditable(false);
        txtDescriptor.setColumns(20);
        panelDescriptor.add(txtDescriptor, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        panelL.add(panelDescriptor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel.add(panelL, gridBagConstraints);

        panlR.setBackground(new java.awt.Color(230, 126, 34));
        panlR.setLayout(new java.awt.GridBagLayout());

        jlSubjectsR.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlSubjectsRValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jlSubjectsR);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panlR.add(jScrollPane2, gridBagConstraints);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Danh sách môn học");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panlR.add(jLabel34, gridBagConstraints);

        Info.setBackground(new java.awt.Color(230, 126, 34));
        Info.setLayout(new java.awt.GridLayout(3, 1, 0, 12));

        txtAverageR.setEditable(false);
        txtAverageR.setColumns(20);
        Info.add(txtAverageR);

        txtStatusR.setEditable(false);
        txtStatusR.setColumns(20);
        Info.add(txtStatusR);

        txtTeacherName.setEditable(false);
        txtTeacherName.setColumns(20);
        txtTeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherNameActionPerformed(evt);
            }
        });
        Info.add(txtTeacherName);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panlR.add(Info, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        panel.add(panlR, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(111, 30, 81));
        jLabel32.setText("Thông tin sinh viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panel.add(jLabel32, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(111, 30, 81));
        jLabel33.setText("Tiến độ học tập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panel.add(jLabel33, gridBagConstraints);

        Cards.add(panel, "cardProfile");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(Cards, gridBagConstraints);

        setBounds(0, 0, 1207, 504);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(Cards, "cardNews");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(Cards, "cardGrade");
    }//GEN-LAST:event_btnGradeActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
        cardLayout.show(Cards, "cardAttendance");
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        cardLayout.show(Cards, "cardProfile");
    }//GEN-LAST:event_btnProfileActionPerformed

    private void txtQuiz6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuiz6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuiz6ActionPerformed

    private void txtLab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLab5ActionPerformed

    private void jlListSubjectsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlListSubjectsValueChanged
        // TODO add your handling code here:
        displayMarks();
    }//GEN-LAST:event_jlListSubjectsValueChanged

    private void txtSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexActionPerformed

    private void openLoad() {
        load = LoadingDialog.init(this);
        load.setVisible(true);
    }
    
    private void jlSubjectsRValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlSubjectsRValueChanged
        // TODO add your handling code here:
        displayInfoSubjectResult();
        displayInfoTeacher();
    }//GEN-LAST:event_jlSubjectsRValueChanged

    private void txtTeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherNameActionPerformed

    private void designButton(JButton originButton, int bgHex, int fgHex, int t, int r, int b, int l) {
        originButton.setBackground(new Color(bgHex));
        originButton.setForeground(new Color(fgHex));
        originButton.setBorder(new EmptyBorder(t, l, b, r));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView("dungbhph00002@fpt.edu.vn").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JPanel Info;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnGrade;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlListSubjects;
    private javax.swing.JList<String> jlSubjectsR;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNameStudent;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelASM1;
    private javax.swing.JPanel panelASM2;
    private javax.swing.JPanel panelASMFinal;
    private javax.swing.JPanel panelAttendance;
    private javax.swing.JPanel panelAverage;
    private javax.swing.JPanel panelBatch;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelDescriptor;
    private javax.swing.JPanel panelDob;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelEmail3;
    private javax.swing.JPanel panelGrade;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelJoinDate;
    private javax.swing.JPanel panelL;
    private javax.swing.JPanel panelLab1;
    private javax.swing.JPanel panelLab2;
    private javax.swing.JPanel panelLab3;
    private javax.swing.JPanel panelLab4;
    private javax.swing.JPanel panelLab5;
    private javax.swing.JPanel panelLab6;
    private javax.swing.JPanel panelLab7;
    private javax.swing.JPanel panelLab8;
    private javax.swing.JPanel panelListSubjects;
    private javax.swing.JPanel panelNews;
    private javax.swing.JPanel panelPhoneNumber;
    private javax.swing.JPanel panelQuiz1;
    private javax.swing.JPanel panelQuiz2;
    private javax.swing.JPanel panelQuiz3;
    private javax.swing.JPanel panelQuiz4;
    private javax.swing.JPanel panelQuiz5;
    private javax.swing.JPanel panelQuiz6;
    private javax.swing.JPanel panelQuiz7;
    private javax.swing.JPanel panelQuiz8;
    private javax.swing.JPanel panelSex;
    private javax.swing.JPanel panelSpecificallyMajor;
    private javax.swing.JPanel panlR;
    private javax.swing.JTextField txtASM1;
    private javax.swing.JTextField txtASM2;
    private javax.swing.JTextField txtASMFinal;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtAverageR;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtDescriptor;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJoinDate;
    private javax.swing.JTextField txtLab1;
    private javax.swing.JTextField txtLab2;
    private javax.swing.JTextField txtLab3;
    private javax.swing.JTextField txtLab4;
    private javax.swing.JTextField txtLab5;
    private javax.swing.JTextField txtLab6;
    private javax.swing.JTextField txtLab7;
    private javax.swing.JTextField txtLab8;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtProvice;
    private javax.swing.JTextField txtQuiz1;
    private javax.swing.JTextField txtQuiz2;
    private javax.swing.JTextField txtQuiz3;
    private javax.swing.JTextField txtQuiz4;
    private javax.swing.JTextField txtQuiz5;
    private javax.swing.JTextField txtQuiz6;
    private javax.swing.JTextField txtQuiz7;
    private javax.swing.JTextField txtQuiz8;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtSpecificallyMajor;
    private javax.swing.JTextField txtStatusR;
    private javax.swing.JTextField txtTeacherName;
    // End of variables declaration//GEN-END:variables

    private void initSubjectForGrade() {
        listSubjectForGrade = service.getSubjectBySParticipation(studentObj.getStudentID());

        if (listSubjectForGrade != null) {
            mapSubjectForGrade = new TreeMap<>();
            for (SubjectDetail o : listSubjectForGrade) {
                mapSubjectForGrade.put(o.getSubjectName() + " - " + o.getSubjectCode(), o.getSubjectDetailID());
            }

            jlListSubjects.setModel(modelSubjectForGrade);
            modelSubjectForGrade.removeAllElements();
            for (Map.Entry<String, Integer> entry : mapSubjectForGrade.entrySet()) {
                modelSubjectForGrade.addElement(entry.getKey());
            }
        }
    }

    private void displayMarks() {
        if (jlListSubjects.getSelectedIndices().length == 1) {
            int subjectID = mapSubjectForGrade.get(jlListSubjects.getSelectedValue());
            int studentID = studentObj.getStudentID();

            grade = service.getGradeForSubjectID(subjectID, studentID);
            Login.load.dispose();
            double lab1, lab2, lab3, lab4, lab5, lab6, lab7, lab8;
            double quiz1, quiz2, quiz3, quiz4, quiz5, quiz6, quiz7, quiz8;
            double assignment1, assignment2, assignmentFinal;

            txtLab1.setText((lab1 = grade.getLab1()) + "");
            txtLab2.setText((lab2 = grade.getLab2()) + "");
            txtLab3.setText((lab3 = grade.getLab3()) + "");
            txtLab4.setText((lab4 = grade.getLab4()) + "");
            txtLab5.setText((lab5 = grade.getLab5()) + "");
            txtLab6.setText((lab6 = grade.getLab6()) + "");
            txtLab7.setText((lab7 = grade.getLab7()) + "");
            txtLab8.setText((lab8 = grade.getLab8()) + "");

            txtQuiz1.setText((quiz1 = grade.getQuiz1()) + "");
            txtQuiz2.setText((quiz2 = grade.getQuiz2()) + "");
            txtQuiz3.setText((quiz3 = grade.getQuiz3()) + "");
            txtQuiz4.setText((quiz4 = grade.getQuiz4()) + "");
            txtQuiz5.setText((quiz5 = grade.getQuiz5()) + "");
            txtQuiz6.setText((quiz6 = grade.getQuiz6()) + "");
            txtQuiz7.setText((quiz7 = grade.getQuiz7()) + "");
            txtQuiz8.setText((quiz8 = grade.getQuiz8()) + "");

            txtASM1.setText((assignment1 = grade.getAssignment1()) + "");
            txtASM2.setText((assignment2 = grade.getAssignment2()) + "");
            txtASMFinal.setText((assignmentFinal = grade.getAssignmentfinal()) + "");

            double average = (lab1 + lab2 + lab3 + lab4 + lab5 + lab6 + lab7 + lab8
                    + quiz1 + quiz2 + quiz3 + quiz4 + quiz5 + quiz6 + quiz7 + quiz8
                    + assignment1 + assignment2 + assignmentFinal) / 19.0;

            txtAverage.setText(new BigDecimal(average).toString());

            if (average >= 5) {
                lblStatus.setText("Qua môn");
            } else {
                lblStatus.setText("Trượt môn");
            }
        }
    }

    private String getMSSV(int StudentID) {
        String defaultStr = "00000" + StudentID;
        String res = "PH" + defaultStr.substring(defaultStr.length() - 5, defaultStr.length());
        return res.toUpperCase();
    }

    private void initInfoStudent() {
        lblStudentID.setText(getMSSV(studentObj.getStudentID()));
        lblNameStudent.setText(studentObj.getStudentName());

        txtEmail.setText(studentObj.getEmail());
        String sex = "";
        if (studentObj.getSex() == 1) {
            sex = "Nam";
        } else {
            sex = "Nữ";
        }
        txtSex.setText(sex);

        txtDob.setText(LocalDate.parse(
                studentObj.getDob().toString()).toString());

        txtJoinDate.setText(LocalDate.parse(studentObj.getLastModified().toString()).toString());
        txtProvice.setText(studentObj.getProvice());
        txtPhoneNumber.setText(studentObj.getPhoneNumber());
        txtSpecificallyMajor.setText(studentObj.getSpecificallyMajorName());
        txtBatch.setText(studentObj.getBatch() + "");
        txtDescriptor.setText(studentObj.getDescriptor());

        byte[] data = studentObj.getPhoto();
        Image img = null;
        if (data != null) {
            try (ByteArrayInputStream bin = new ByteArrayInputStream(data)) {
                img = ImageIO.read(bin);
            } catch (IOException e) {
                System.out.println(e);
            }
        }
        if (img != null) {
            lblImage.setIcon(new ImageIcon(img.getScaledInstance(120, 120, Image.SCALE_SMOOTH)));
        } else {
            lblImage.setText("NOTHING");
        }

    }

    private void initListSubjectHaveStudied() {
        listSubjectHaveStudied
                = service.getSubjectBySParticipation(studentObj.getStudentID());

        mapSubjectHaveStudied = new TreeMap<>();
        if (listSubjectHaveStudied != null) {
            for (SubjectDetail o : listSubjectHaveStudied) {
                mapSubjectHaveStudied.put(o.getSubjectName(), o.getSubjectDetailID());
            }
        }

        jlSubjectsR.setModel(modelSubjectHaveStudied);
        for (Map.Entry<String, Integer> entry : mapSubjectHaveStudied.entrySet()) {
            modelSubjectHaveStudied.addElement(entry.getKey());
        }
    }

    private void displayInfoSubjectResult() {
        int subjectDetailID = mapSubjectHaveStudied.get(jlSubjectsR.getSelectedValue());

//        for (SubjectDetail o : listSubjectHaveStudied) {
//            if(o.getSubjectDetailID() == subjectDetailID) {
//                
//            }
//        }
        Grade o = service.getGradeForSubjectID(subjectDetailID, studentObj.getStudentID());
        System.out.println(subjectDetailID);
        double sum = o.getLab1() + o.getLab2() + o.getLab3() + o.getLab4() + o.getLab5() + o.getLab6() + o.getLab7()
                + o.getLab8() + o.getQuiz1() + o.getQuiz2() + o.getQuiz3() + o.getQuiz4() + o.getQuiz5() + o.getQuiz6()
                + o.getQuiz7() + o.getQuiz8() + o.getAssignment1() + o.getAssignment2() + o.getAssignmentfinal();
        txtAverageR.setText("Điểm trung bình: " + (sum / 19));
        if ((sum / 19) >= 5) {
            txtStatusR.setText("Trạng thái: Qua môn");
        } else {
            txtStatusR.setText("Trạng thái: Trượt");
        }
    }

    private void displayInfoTeacher() {
        if (jlSubjectsR.getSelectedIndices().length == 1) {
            String value = jlSubjectsR.getSelectedValue();
            int subjectDetailID = mapSubjectHaveStudied.get(value);
            String teacherName = service.getTeacherNameBySubjectAndStudent(subjectDetailID, studentObj.getStudentID());
            txtTeacherName.setText(teacherName);
            System.out.println(teacherName);
        }

    }

}
