package view.ultilities;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static view.login.Login.load;

/**
 *
 * @author nguye
 */
public class Management extends javax.swing.JDialog {

    /**
     * Creates new form StudyParticipation
    
    */
    private boolean isManager;
    private final boolean isAdmin;
    
    public Management(java.awt.Frame parent, boolean modal, boolean isManager, boolean isAdmin) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(0xd35400));
        setLocationRelativeTo(parent);

        this.isManager = isManager;
        this.isAdmin = isAdmin;
        
        if(!isManager) {
            jmiEmployeeManagement.setVisible(false);
        } else{
            jmiEmployeeManagement.setVisible(true);
        }
        
        jmiCreateStudyParticipation.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmTeacher = new javax.swing.JMenu();
        jmStudent = new javax.swing.JMenu();
        jmTool = new javax.swing.JMenu();
        jmiCreateTeachingAsm = new javax.swing.JMenuItem();
        jmiCreateStudyParticipation = new javax.swing.JMenuItem();
        jmiEmployeeManagement = new javax.swing.JMenuItem();
        jmWindow = new javax.swing.JMenu();
        jmiEquipment = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Welcom to School Management");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        jMenu1.setText("View");

        jMenuItem4.setText("View Student");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("View Teacher");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jmTeacher.setText("Teacher");
        jMenuBar1.add(jmTeacher);

        jmStudent.setText("Student");
        jMenuBar1.add(jmStudent);

        jmTool.setText("Tool");

        jmiCreateTeachingAsm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiCreateTeachingAsm.setText("Create TeachingASM");
        jmiCreateTeachingAsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateTeachingAsmActionPerformed(evt);
            }
        });
        jmTool.add(jmiCreateTeachingAsm);

        jmiCreateStudyParticipation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiCreateStudyParticipation.setText("Create Study Participation");
        jmiCreateStudyParticipation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCreateStudyParticipationActionPerformed(evt);
            }
        });
        jmTool.add(jmiCreateStudyParticipation);

        jmiEmployeeManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiEmployeeManagement.setText("Employee Management");
        jmiEmployeeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmployeeManagementActionPerformed(evt);
            }
        });
        jmTool.add(jmiEmployeeManagement);

        jMenuBar1.add(jmTool);

        jmWindow.setText("Window");

        jmiEquipment.setText("Equipment");
        jmiEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEquipmentActionPerformed(evt);
            }
        });
        jmWindow.add(jmiEquipment);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiExit.setText("Exit");
        jmWindow.add(jmiExit);

        jMenuBar1.add(jmWindow);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 648, 437);
    }// </editor-fold>//GEN-END:initComponents

    private void displayEmployeeManager(){
        new EmployeeManagement(this, false, isAdmin).setVisible(true);
    }
    
    private void jmiCreateTeachingAsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCreateTeachingAsmActionPerformed
        // TODO add your handling code here:
        new Thread(new Runnable() {
            @Override
            public void run() {
                openLoad();
            }
        }).start();
        new Thread(new Runnable() {
            @Override
            public void run() {
                displayArrangeTeaching();
            }
        }).start();
    }//GEN-LAST:event_jmiCreateTeachingAsmActionPerformed


    private void jmiCreateStudyParticipationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCreateStudyParticipationActionPerformed
        // TODO add your handling code here:
        new Thread(new Runnable() {
            @Override
            public void run() {
                openLoad();
            }
        }).start();
        new Thread(new Runnable() {
            @Override
            public void run() {
                displayStudyingParticipation();
            }
        }).start();

    }//GEN-LAST:event_jmiCreateStudyParticipationActionPerformed

    private void jmiEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEquipmentActionPerformed
        // TODO add your handling code here:
        new Thread(new Runnable() {
            @Override
            public void run() {
                openLoad();
            }
        }).start();
        new Thread(new Runnable() {
            @Override
            public void run() {
                displayEquipmentView();
            }
        }).start();
    }//GEN-LAST:event_jmiEquipmentActionPerformed

    private void jmiEmployeeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmployeeManagementActionPerformed
        // TODO add your handling code here:
        displayEmployeeManager();
    }//GEN-LAST:event_jmiEmployeeManagementActionPerformed

    private void displayEquipmentView() {
        new Equipment(this, false).setVisible(true);
    }
    
    private void displayArrangeTeaching() {
        new ArrangeTeaching(this, false).setVisible(true);
    }

    private void displayStudyingParticipation() {
        new StudyParticipation(this, false).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudyParticipation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudyParticipation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudyParticipation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudyParticipation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    private void openLoad() {
        load = LoadingDialog.init(this);
        load.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jmStudent;
    private javax.swing.JMenu jmTeacher;
    private javax.swing.JMenu jmTool;
    private javax.swing.JMenu jmWindow;
    private javax.swing.JMenuItem jmiCreateStudyParticipation;
    private javax.swing.JMenuItem jmiCreateTeachingAsm;
    private javax.swing.JMenuItem jmiEmployeeManagement;
    private javax.swing.JMenuItem jmiEquipment;
    private javax.swing.JMenuItem jmiExit;
    // End of variables declaration//GEN-END:variables
}
